import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1> lets build Hulu</h1>

     {/* Header contains links and logo */}
     {/* Nav component -> contains movie genres*/}
    {/* Results component -> consists of individual results*/} 
   

    </div>
  )
}
