import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
     {/* Header contains links and logo */}
     <Header/>
     {/* Nav component -> contains movie genres*/}
    {/* Results component -> consists of individual results*/} 
   

    </div>
  )
}
